/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'venka' at '8/23/16 7:44 PM' with Gradle 2.14
 *
 * @author venka, @date 8/23/16 7:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
